### ISSUE TITLE
eCheck disables CC and vice-versa

### ISSUE THREAD

**Issue by bcobin** [donordepot/com.donordepot.authnetecheck#16]
AFAICT, it looks like an either/or proposition: If you use eCheck, you can't use Authorize.net for credit cards and vice versa. If you try setting up eCheck as a separate payment processor using the same credentials, it replaces the existing Authorize.net payment processor and there's no option for cc# entry on the form.

Am I missing something? Any feedback greatly appreciated… thanks!

**Comment by JoshEpic** [comment]
What version of civicrm are you using?

**Comment by bcobin** [comment]
Thanks for the response and sorry or taking so long to get back - we're on 4.7.16.

**Comment by JoshEpic** [comment]
Thank you. We have tested with earlier versions of 4.7. We will look into this issue but it may be awhile before a fix is in place.

**Comment by bcobin** [comment]
Thanks for getting back, Josh - are you saying that the behavior is confirmed? Do let me know... thanks!

**Comment by JoshEpic** [comment]
We have not tested it yet. I was stating when we made the extension compatible with 4.7 it was compatible on earlier versions. We will look into this but it may be a while.

**Comment by JoshEpic** [comment]
This has been fixed with the release 1.2.1
