### ISSUE TITLE
Successfully enabled v1.1.1 in 4.5 but some issue w/ back-office contribution form

### ISSUE THREAD

**Issue by davecivicrm** [donordepot/com.donordepot.authnetecheck#9]
Seems like the 4.5 api error issue may be resolved now in 1.1.1 ?? I installed succesfully in 4.5.2.

However, when I attempted to use Submit Credit Card contribution, I get a spurious error:
"You will need to configure the live settings for your Payment Processor before you can submit credit card transactions." Even though I have both test and live settings filled in, and a front-end contribution page which I configured to include eCheck works properly. (Maybe this is a known bug / missing feature ??).

I went ahead and enabled the extension for automatic distribution in any case. Let me know if that's not appropriate at this point.

**Comment by jmcclelland** [comment]
We hit a bug that I suspect is related. When I tried to submit a credit card submission I get a white screen and our error log reports a problem with classloader which seems to be related to the call to CRM_Core_BAO_PaymentProcessor::getPayment on line 26 of authnetecheck.php. I think that class was removed in CiviCRM 4.4. I think it should be CRM_Financial_BAO_PaymentProcessor - which means you may need to have some kind of version checking if you want to support both older and newer versions.

**Comment by cruhlen** [comment]
I'm submitting this onto the development team to investigate.  Thanks for
bringing this to our attention.

On Tue, Mar 17, 2015 at 3:55 PM, jmcclelland <notifications@github.com>
wrote:

> We hit a bug that I suspect is related. When I tried to submit a credit
> card submission I get a white screen and our error log reports a problem
> with classloader which seems to be related to the call to
> CRM_Core_BAO_PaymentProcessor::getPayment on line 26 of authnetecheck.php.
> I think that class was removed in CiviCRM 4.4. I think it should be
> CRM_Financial_BAO_PaymentProcessor - which means you may need to have some
> kind of version checking if you want to support both older and newer
> versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/donordepot/com.donordepot.authnetecheck/issues/9#issuecomment-82570107>
> .
>



-- 
Best regards,

Chris Ruhlen

Donor Depot
A Reliant Marketing Solutions Company
*Software and Fundraising Consulting for Nonprofits*

877.85DEPOT | P: 757.335.1693 | chris@donordepot.com <chris@rms7.com> | F:
213.402.5997
www.donordepot.com

**Comment by Prem-Patel** [comment]
I have installed the payment processor on sites. It's working fine for test account but I am not able to make live contribution. Also I am not getting any error under ConfigAndLog folder of civicrm. Below I have mentioned the civicrm version 

Civicrm Version : 4.6.8
Drupal Version : 7

After submitting the confirm donation it redirect to below link


sitename/civicrm/contribute/transact

kindly help me to resolve this  issue.

Thanks You

**Comment by JoshEpic** [comment]
Hello,

I am very sorry but we have not yet tested this extension on 4.6. Because of that and your information that the test credentials are working I would suggest to make sure your live credentials are correct. This would be the main cause of a live transaction not going through. 

Thank you,
Josh

**Comment by Prem-Patel** [comment]
Thanks Josh,

Can you please tell me, is related to php or .tpl file? It will be really helpful for me. Basically, if credential is not valid then it should be redirect to contribution main page with some error message after submitting the confirmation page. 

I am getting the below error in my log file.

[message] => 128 This transaction cannot be processed.


Thank you,
Prem Patel

**Comment by JoshEpic** [comment]
Hello,

Thank you for providing the error. That is actually a common error that people tend to receive during testing or when using the wrong bank account. Below is a snippet of the error code 128 from the AuthNet forums.

> When a customer submits an eCheck transaction, the first thing it does is check the customers bank account against a black list. If the customer's account is on the black list, the error 128 is returned and Authorize.Net does not even attempt to actually process the transaction.
>  
> A customer's bank account gets put on the black list after they make a payment that is returned as no account, wrong account, or unable to locate. There are instructions you can give the customer to get their account off the black list, but I probably shouldn't post them here.

Let me know if that helps.

Thank you,
Josh

**Comment by Prem-Patel** [comment]
Thank you Josh for error code 128 information. Actually i am getting the wsod after contribution confirmation page because of recursion of **error** function. I am getting the below error 

    [_package] => CiviCRM
    [_compat] => 
    [_msgCallback] => Array
        (
            [0] => CRM_Core_Error Object
 *RECURSION*
            [1] => getErrorMessage
        )

    [_contextCallback] => Array
        (
            [0] => CRM_Core_Error Object
 *RECURSION*
            [1] => getFileLine
        )

Please help me, why I am getting this recursion issue. 

Thanks
Prem Patel

**Comment by Prem-Patel** [comment]
Basically, below function is creating wsod issue. But I am not able to resolve this issue.

    function &error($errorCode = NULL, $errorMessage = NULL) {
     $e = CRM_Core_Error::singleton();
     if ($errorCode) {
       $e->push($errorCode, 0, NULL, $errorMessage);
     }
     else {
       $e->push(9001, 0, NULL, 'Unknown System Error.');
     }
    return $e;
  }

Will you please help me to resolve this issue.

Thanks 
Prem
